package org.prg.twofactorauth.webauthn.model;

import java.util.Set;
import java.util.UUID; /**
 * Basic representation of a user that is exposed outside this package. It is used to associate a set of FIDO
 * credentials i.e. authenticators that can be used to log in a user. For example, the user can configure thier
 * account to log in with faceID from an iPhone and using a YubiKey and using the fingerprint scanner on a laptop.
 *
 * Manipulating a UserAccount is done via an instance of a UserService
 *
 * @param id the unique uuid that identifies the user, this value is auto generated by UserService
 * @param displayName the username that will be displayed publicly to other users
 * @param email the email address of the user they will login with this email
 * @param credentials a set of fido credentials that the user can login with.
 */
public class UserAccount{

    private String id;
    private String displayName;
    private String email;
    private  Set<FidoCredential> credentials;

    public UserAccount(String id, String displayName, String email, Set<FidoCredential> credentials) {
        this.id = id;
        this.displayName = displayName;
        this.email = email;
        this.credentials = credentials;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set<FidoCredential> getCredentials() {
        return credentials;
    }

    public void setCredentials(Set<FidoCredential> credentials) {
        this.credentials = credentials;
    }
}